repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

#  - repo: https://github.com/golangci/golangci-lint
#    rev: v1.57.2
#    hooks:
#      - id: golangci-lint
#        name: golangci-lint-root
#        entry: bash -c 'golangci-lint run'

#      - id: golangci-lint
#        name: golangci-lint-subdir
#        entry: bash -c 'cd subtest && golangci-lint run --config $OLDPWD/.golangci.yml'
